'use strict';
function createJobView({document,window}){
 const el=id=>document.getElementById(id);let selected=null,report=null,unitMetric=true,last=0,pending=false,seen=null;
 const write=(id,value)=>{el(id).textContent=value;};
 const km=v=>v==null?'—':(unitMetric?v:v/1.609344).toFixed(1)+(unitMetric?' km':' mi');
 const money=(v,game)=>v==null?'—':game==='unknown'?String(v)+' game currency':new Intl.NumberFormat(undefined,{style:'currency',currency:game==='ats'?'USD':'EUR',maximumFractionDigits:0}).format(v);
 const time=seconds=>seconds==null?'—':Math.floor(seconds/3600)+'h '+Math.floor(seconds%3600/60)+'m';
 function drawRoute(){const canvas=el('job-route'),box=canvas.getBoundingClientRect();if(!box.width)return;const ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=box.width*ratio;canvas.height=280*ratio;const c=canvas.getContext('2d');if(!c)return;c.scale(ratio,ratio);c.fillStyle='#101b20';c.fillRect(0,0,box.width,280);const points=(report?.route||[]).filter(Boolean);if(!points.length){c.fillStyle='#9bb0b5';c.font='14px system-ui';c.fillText('No recorded world positions',20,35);return;}
 let minX=Infinity,minZ=Infinity,maxX=-Infinity,maxZ=-Infinity;for(const p of points){minX=Math.min(minX,p[0]);minZ=Math.min(minZ,p[1]);maxX=Math.max(maxX,p[0]);maxZ=Math.max(maxZ,p[1]);}
 const scale=Math.min((box.width-56)/Math.max(maxX-minX,20),224/Math.max(maxZ-minZ,20)),project=p=>[box.width/2+(p[0]-(minX+maxX)/2)*scale,140+(p[1]-(minZ+maxZ)/2)*scale];
 c.beginPath();let pen=false;for(const p of report.route){if(!p){pen=false;continue;}const q=project(p);if(pen)c.lineTo(...q);else c.moveTo(...q);pen=true;}c.lineWidth=3;c.strokeStyle='#91d3c7';c.stroke();
 for(const [point,label,color]of [[points[0],'START','#d5e9a3'],[points.at(-1),'END','#ffc489']]){const [x,y]=project(point);c.fillStyle=color;c.beginPath();c.arc(x,y,5,0,Math.PI*2);c.fill();c.font='10px system-ui';c.fillText(label,x+9,y-8);}
 }
 function render(){if(!report)return;const official=report.official||{},litres=report.fuel_available===false?null:report.fuel_used_l,distance=report.distance_available===false?null:report.distance_km;
 write('job-title',report.origin+' → '+report.destination);write('job-subtitle',report.cargo+' · '+(report.cargo_mass_kg/1000).toFixed(1)+' t · '+report.truck);write('job-outcome',report.outcome);
 const values={ 'job-distance':km(official.distance_km??distance),'job-observed-distance':km(distance),'job-revenue':money(official.revenue,report.game),'job-xp':official.earned_xp??'—','job-duration':official.game_minutes==null?'—':time(official.game_minutes*60),'job-observed-time':time(report.observed_seconds),'job-fuel':litres==null?'—':(unitMetric?litres:litres/3.785411784).toFixed(1)+(unitMetric?' L':' gal'),'job-economy':litres!=null&&distance>0?(unitMetric?litres/distance*100:distance/1.609344/(litres/3.785411784)).toFixed(1)+(unitMetric?' L/100 km':' mpg'):'—','job-peak':report.speed_available===false?'—':(unitMetric?report.peak_speed_kmh:report.peak_speed_kmh/1.609344).toFixed(0)+(unitMetric?' km/h':' mph'),'job-average':report.speed_available===false?'—':(unitMetric?report.average_speed_kmh:report.average_speed_kmh/1.609344).toFixed(0)+(unitMetric?' km/h':' mph'),'job-idle':time(report.idle_seconds),'job-overspeed':report.speed_limit_available===false?'—':time(report.overspeed_seconds),'job-cargo':official.cargo_damage??report.cargo_damage_end,'job-parking':official.autopark==null?'—':official.autopark?'Automatic parking':'Manual parking','job-loading':official.autoload==null?'—':official.autoload?'Automatic loading':'Manual loading'};
 values['job-cargo']=values['job-cargo']==null?'—':((1-values['job-cargo'])*100).toFixed(1)+'%';for(const [id,value]of Object.entries(values))write(id,String(value));
 const stamp=value=>value?new Date(value).toLocaleString():'—';write('job-dates','Recording started: '+stamp(report.started_at_ms)+' · Completed: '+stamp(report.finished_at_ms));
 const fuel=value=>value==null?'—':(unitMetric?value:value/3.785411784).toFixed(1)+(unitMetric?' L':' gal');const wear=report.wear_start==null||report.wear_end==null?'—':((report.wear_end-report.wear_start)*100).toFixed(2)+' percentage points';write('job-extra','Refuelled: '+fuel(report.fuel_available===false?null:report.refuelled_l)+' · Maximum component wear change: '+wear+' · Cancellation penalty: '+money(official.cancel_penalty,report.game));
 const costs=category=>(report[category]||[]).map(e=>money(e.amount,report.game)).join(' + ')||'None observed';write('job-costs','Fines: '+costs('fines')+' · Tolls: '+costs('tolls')+' · Ferry/train: '+costs('transport_costs'));
 write('job-coverage',report.coverage+' Gaps: '+report.gaps+' · skipped frames: '+report.dropped_frames+' · downsampled route points: '+report.route_samples_dropped+'.');el('job-detail').hidden=false;drawRoute();
 }
 async function select(id){try{const r=await window.fetch('/api/jobs/'+id,{cache:'no-store'});if(!r.ok)throw Error('Report unavailable');report=await r.json();selected=id;render();}catch(e){write('jobs-status',e.message);}}
 async function refresh(force=false){if(pending||!window.fetch||!force&&Date.now()-last<2000)return;pending=true;last=Date.now();try{const response=await window.fetch('/api/jobs',{cache:'no-store',signal:window.AbortSignal?.timeout(2000)});if(!response.ok)throw Error('Job journal unavailable');const data=await response.json();
 write('jobs-status',data.error|| (data.recording?'Recording '+data.recording.origin+' → '+data.recording.destination+' · saved by the local service':data.reports.length?'Completed jobs are saved locally.':'Your completed jobs will appear here. Recording continues with this window closed.'));
 const signature=JSON.stringify(data.reports);if(signature!==seen){seen=signature;const list=el('job-list');list.replaceChildren();for(const summary of data.reports){const button=document.createElement('button');button.type='button';button.textContent=summary.origin+' → '+summary.destination+' · '+summary.outcome;button.addEventListener('click',()=>select(summary.id));list.append(button);}if(data.reports.length&&data.reports[0].id!==selected){el('job-badge').hidden=false;write('job-badge','New job report');el('job-badge').onclick=()=>{el('tab-jobs').click();select(data.reports[0].id);el('job-badge').hidden=true;};if(selected===null)await select(data.reports[0].id);}}
 }catch(e){write('jobs-status',e.message);}finally{pending=false;}}
 el('job-export').addEventListener('click',()=>{if(!report)return;const blob=new window.Blob([JSON.stringify(report,null,2)],{type:'application/json'}),url=window.URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='haulsense-job-'+report.id+'.json';a.click();window.setTimeout(()=>window.URL.revokeObjectURL(url),2000);});
 window.addEventListener('resize',drawRoute);return {refresh,drawRoute,units(metric){if(unitMetric!==metric){unitMetric=metric;render();}}};
}
if(typeof module!=='undefined')module.exports={createJobView};
