// Optional real-browser check against a detailed ATS map and an isolated mock daemon.
const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1500,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const mapPath=process.argv[2],baseUrl=process.argv[3]||'http://127.0.0.1:39076';if(!mapPath)throw Error('Usage: node tests/browser-scene.cjs scene.json [mock dashboard URL]');const data=JSON.parse(fs.readFileSync(mapPath));const edge=data.graph.edges.find(e=>e[3]&&e[3][0][0]<-104000&&e[3][0][0]>-105000&&e[3][0][1]>6000&&e[3][0][1]<9000);const node=data.graph.nodes[edge[0]],uids=[data.graph.nodes[edge[0]][3],data.graph.nodes[edge[1]][3]];let fresh=true,active=true,game='ats',ids=uids;
await page.route('**/api/state',async route=>{let s=await(await route.fetch()).json();s.active=active;s.demo=false;s.telemetry={...s.telemetry,game,world_position:[node[0],node[2]+2,node[1]],heading:.75,destination:'Los Angeles'};await route.fulfill({json:s});});
await page.route('**/api/route',route=>route.fulfill({json:{source:'ets2la',available:true,fresh,node_uids:ids}}));await page.goto(baseUrl);await page.evaluate(map=>navigatorView.loadMap(map),JSON.parse(fs.readFileSync(mapPath,'utf8')));await page.waitForFunction(()=>document.querySelector('#route-status').textContent.includes('Game GPS route'),null,{timeout:60000});
const perf=await page.evaluate(()=>{const durations=[];for(let i=0;i<10;i++){const start=performance.now();navigatorView.draw();durations.push(performance.now()-start);}return {durations,stats:navigatorView.stats()};});console.log('Render performance',perf);fs.writeFileSync('build/scene-render-metrics.json',JSON.stringify(perf));
active=false;await page.waitForFunction(()=>document.querySelector('#road-scene').hidden);active=true;fresh=false;await page.waitForFunction(()=>document.querySelector('#route-status').textContent.includes('calculated on mapped roads'));
ids=['ffffffffffffffff','fffffffffffe'];fresh=true;await page.waitForFunction(()=>document.querySelector('#gps-status').textContent.includes('do not match'));await page.waitForFunction(()=>document.querySelector('#route-status').textContent.includes('calculated on mapped roads'));
game='ets2';await page.waitForFunction(()=>document.querySelector('#road-scene').hidden);game='ats';await page.waitForFunction(()=>!document.querySelector('#road-scene').hidden);
await page.evaluate(()=>document.querySelector('#road-scene').getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await page.waitForFunction(()=>document.querySelector('#scene-status').textContent.includes('WebGL unavailable'));assert(await page.locator('#road-scene').isHidden());
console.log('GPS source, expiry, UID mismatch, pause, game mismatch and lost-context fallback passed',errors);assert.equal(errors.length,0);await browser.close();})();
