// Optional real Electron qualification with a locally exported map. Requires Playwright via NODE_PATH.
const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const profile='/tmp/haulsense-desktop-review-'+Date.now();fs.mkdirSync(profile);const app=await electron.launch({executablePath:process.cwd()+'/ats-dualsense/desktop/node_modules/electron/dist/electron',args:[process.cwd()+'/ats-dualsense/desktop','--demo'],env:{...process.env,HAULSENSE_TEST_PROFILE:profile},timeout:30000});const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('DEMO'));
console.log('desktop',await page.title(),await page.url());console.log(await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];return {sandbox:w.webContents.getLastWebPreferences().sandbox,node:w.webContents.getLastWebPreferences().nodeIntegration,throttle:w.webContents.backgroundThrottling};}));
console.log('prefs',await page.evaluate(()=>({node:typeof require,location:location.protocol,visibility:document.visibilityState})));
assert.equal(await page.locator('input[type=file]').count(),0);await page.waitForFunction(()=>document.querySelector('#map-storage').dataset.mapReady==='true',null,{timeout:60000});await page.waitForTimeout(500);await page.screenshot({path:'build/standalone-desktop-demo.png'});const before=await page.evaluate(()=>state.sequence);
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].minimize());await new Promise(r=>setTimeout(r,1500));const after=await page.evaluate(()=>state.sequence);assert(after>before);console.log('minimized sequence advanced',before,after);
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].restore());await page.evaluate(()=>window.HaulSenseStorage.saveMap(new Blob([JSON.stringify({version:1,game:'ets2',coordinates:'scs-xz-metres',roads:[]})]),'obsolete-cache.json'));await page.reload();await page.waitForFunction(()=>document.querySelector('#map-storage').dataset.mapReady==='true',null,{timeout:60000});assert.equal(await page.locator('#map-unload').count(),0);assert(await page.locator('#route-destination option').count()>200);console.log('embedded map restored; incompatible legacy cache ignored');
await page.locator('#tab-jobs').click();await page.waitForTimeout(300);await page.screenshot({path:'build/standalone-job-empty.png'});console.log('errors',errors);assert.equal(errors.length,0);await app.close();const reopened=await electron.launch({executablePath:process.cwd()+'/ats-dualsense/desktop/node_modules/electron/dist/electron',args:[process.cwd()+'/ats-dualsense/desktop','--demo'],env:{...process.env,HAULSENSE_TEST_PROFILE:profile},timeout:30000});const restored=await reopened.firstWindow();await restored.waitForFunction(()=>document.querySelector('#map-storage').dataset.mapReady==='true',null,{timeout:60000});console.log('map restored after full app restart');await reopened.close();})();
