import {createRequire} from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const {parseHTML}=createRequire(import.meta.url)('linkedom');
const {window,document}=parseHTML(fs.readFileSync(new URL('../ats-dualsense/ui/index.html',import.meta.url),'utf8'));
const canvas=document.getElementById('navigation-map');canvas.getBoundingClientRect=()=>({width:400,height:390});
const marks=[];canvas.getContext=()=>new Proxy({}, {get:(_,key)=>(...args)=>{if(key==='translate')marks.push(args);}});
const context=vm.createContext({document,window,console,module:{exports:{}}});
vm.runInContext(fs.readFileSync(new URL('../ats-dualsense/ui/navigation.js',import.meta.url),'utf8'),context);
const nav=context.module.exports.createNavigator({document,window});
const s={active:true,demo:false,sequence:1,telemetry:{game:'ats',world_position:[100,42,-200],heading:.75,pitch:.01,roll:-.01,odometer:1000,nav_distance:200000,nav_time:3600,fuel_range:150,cargo_damage:.1,trailer_connected:true}};
nav.update(s);
assert.match(document.getElementById('map-heading').textContent,/90°/);
assert.match(document.getElementById('journey-margin').textContent,/-50 km/);
assert.match(document.getElementById('journey-advice').textContent,/fuel stop/);
assert.match(document.getElementById('journey-cargo').textContent,/90%/);
assert.deepEqual(marks.at(-1),[200,269.09999999999997]);
s.sequence++;s.telemetry.odometer=1012;nav.update(s,false);
assert.equal(document.getElementById('journey-driven').textContent,'7.5 mi');
assert.throws(()=>nav.loadMap({version:1,game:'ats',coordinates:'wgs84',roads:[]}));
assert.throws(()=>nav.loadMap({version:1,game:'ats',coordinates:'scs-xz-metres',roads:[[[0,0],[NaN,2]]]}));
nav.loadMap({version:1,game:'ets2',coordinates:'scs-xz-metres',roads:[[[0,0],[100,100]]],labels:[]});
assert.match(document.getElementById('map-note').textContent,/does not match/);
nav.loadMap({version:1,game:'ats',coordinates:'scs-xz-metres',name:'<unsafe>',roads:[[[0,0],[100,100]]],labels:[{position:[100,-200],name:'Test city'}]});
assert.equal(document.getElementById('map-source').textContent,'<unsafe>');
assert.equal(document.getElementById('map-source').children.length,0);
s.active=false;nav.update(s);assert.equal(document.getElementById('map-heading').textContent,'—');assert.equal(document.getElementById('journey-margin').textContent,'—');assert.equal(document.getElementById('map-empty').hidden,false);
s.active=true;s.telemetry.world_position=[0,0,1e20];nav.update(s);assert.equal(document.getElementById('map-empty').hidden,false);
s.telemetry.world_position=null;nav.update(s);assert.match(document.getElementById('map-empty-detail').textContent,/current plugin/);
console.log('Navigation: heading, fuel warning, cargo, odometer/US units, map validation, game mismatch, safe labels and stale/invalid position passed.');

const rich={version:2,game:'ats',coordinates:'scs-xz-metres',roads:[[[0,0,0],[10,10,1]]],templates:[],prefabs:[],assets:[],objects:[],signDefinitions:[],signs:[],barriers:[],pois:[],graph:{nodes:[[0,0,0,'ffffffffffffffff'],[10,10,1,'2']],edges:[[0,1,20,[[0,0,0],[10,10,1]]]]}};
nav.validateMap(rich);
assert.throws(()=>nav.validateMap({...rich,graph:{...rich.graph,edges:[[0,2,20]]}}));
assert.throws(()=>nav.validateMap({...rich,objects:[[42,0,0,0,0,1,1,1]]}));
assert.throws(()=>nav.validateMap({...rich,signs:[[0,0,0,0,-1,42]]}));
console.log('Detailed scene: graph reference, model index and sign text validation passed.');

assert.throws(()=>nav.validateMap({...rich,roadStyles:[[1e7,1,0,0,0]]}));
assert.throws(()=>nav.validateMap({...rich,roadStyles:[[1.5,1,0,0,0]]}));
