import {createRequire} from 'node:module';
const {parseHTML}=createRequire(import.meta.url)('linkedom');
import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../ats-dualsense/ui/index.html',import.meta.url),'utf8');
const {window,document}=parseHTML(html);
for(const input of document.querySelectorAll('input,select'))Object.defineProperty(input,'value',{value:input.getAttribute('value')||'',writable:true});
document.getElementById('units').value='metric';
const canvas=document.getElementById('history');canvas.getBoundingClientRect=()=>({width:800});canvas.getContext=()=>({scale(){},beginPath(){},moveTo(){},lineTo(){},stroke(){}});
window.devicePixelRatio=1;
const pending=[];
const context=vm.createContext({document,window,console,Map,Number,String,Math,Object,JSON,Date,AbortSignal,setTimeout:fn=>{pending.push(fn);return 1;},clearTimeout(){},fetch:async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(process.argv[2] || 'build/ui-state.json','utf8'))})});
vm.runInContext(html.split('<script>')[1].split('</script>')[0],context);
await new Promise(resolve=>setTimeout(resolve,20));
assert.equal(document.getElementById('truck-name').textContent,'Kenworth W900');
assert.equal(document.getElementById('status').textContent,'DEMO · simulated truck');
assert.equal(document.getElementById('wheels').children.length,6);
assert.equal(document.querySelectorAll('.slider-row').length,8);
assert.equal(document.querySelectorAll('.toggle-row').length,8);
vm.runInContext("view='channels';render(state)",context);
assert.ok(document.getElementById('channel-rows').children.length>=89);
vm.runInContext("metric=false;render(state)",context);
assert.equal(document.getElementById('speed-unit').textContent,'mph');
assert.ok(document.getElementById('fuel').textContent.includes('gal'));
vm.runInContext("state.active=false;render(state)",context);
assert.equal(document.getElementById('speed').textContent,'—');
assert.equal(document.getElementById('wheels').children.length,0);
assert.equal(document.getElementById('status').textContent,'DEMO · simulated truck');
console.log('DOM smoke: dashboard, demo labelling, wheels, tuning, channels, US units, stale clearing passed (no visual rendering).');
